[versions]
agp = "8.3.2"
annotationVersion = "1.8.1"
annotation = "0.3.0"
converterGson = "2.9.0"
converterScalars = "2.4.0"
coreSplashscreen = "1.0.1"
hiltAndroid = "2.51.1"
hiltCore = "2.51.1"
hiltNavigationCompose = "1.2.0"
json = "20220320"
kotlin = "1.9.23"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinStdlib = "2.0.0"
kotlinxCoroutinesCore = "1.8.1"
lifecycleRuntimeCompose = "2.8.4"
lifecycleRuntimeKtxVersion = "2.6.2"
lifecycleService = "2.8.4"
loggingInterceptor = "4.11.0"
lottieCompose = "6.4.1"
mapsCompose = "6.1.0"
material = "1.12.0"
constraintlayout = "2.1.4"
materialZ = "1.7.0-beta06"
mockitoInline = "5.2.0"
mockitoKotlin = "5.2.1"
mockitoCore = "5.7.0"
navigationCompose = "2.7.7"
navigationFragmentKtx = "2.7.7"
navigationUiKtx = "2.7.7"
okhttpVersion = "4.12.0"
roomRuntime = "2.6.1"
turbine = "0.12.3"
ksp-version = "1.9.22-1.0.17"
hilt-version = "2.51.1"
hiltAndroidGradlePlugin = "2.51.1"
composeBom = "2024.06.00"
activityCompose = "1.9.1"
viewModelCompose = "2.8.4"
lifecycleRuntimeKtx = "2.8.4"
jetbrainsKotlinJvm = "1.9.22"
coreTesting = "2.2.0"
retrofit = "2.9.0"
okhttp = "5.0.0-alpha.2"
coil = "2.6.0"
logging = "4.11.0"



[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotationVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-runtime-ktx-v262 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeCompose" }
androidx-material-z = { module = "androidx.compose.material:material-*", version.ref = "materialZ" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }

androidx-retrofit2-retrofit = { group = "com.squareup.retrofit2" , name = "retrofit" , version.ref = "retrofit"}
androidx-retrofit2-okhttp = { group = "com.squareup.okhttp3" , name = "okhttp" , version.ref = "okhttp"}
androidx-retrofit2-gson-converter = { group = "com.squareup.retrofit2" , name = "converter-gson" , version.ref = "retrofit"}
androidx-squareup-okhttp-logging = { group = "com.squareup.okhttp3" , name = "logging-interceptor" , version.ref = "logging"}
androidx-coil-compose = { group = "io.coil-kt" , name = "coil-compose" , version.ref = "coil"}

converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }

converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltCore" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-v244 = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCore" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hiltCore" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
logging-interceptor-v480 = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
okhttp-v4120 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-live-data-compose = { group = "androidx.lifecycle" , name = "lifecycle-viewmodel-compose" , version.ref = "viewModelCompose"}
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleService" }
#annotation = { module = "org.mockito4kotlin:annotation", version.ref = "annotation" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

